# roles/kibana/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_kibana_namespace }}"
    - "{{ openio_kibana_sysconfig_dir }}/kibana-{{ openio_kibana_serviceid }}"
    - "{{ openio_kibana_volume }}/optimize"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "/var/log/oio/sds/{{ openio_kibana_namespace }}/kibana-{{ openio_kibana_serviceid }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0750
    recurse: true
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "kibana.yml.j2"
      dest: "{{ openio_kibana_sysconfig_dir }}/\
        kibana-{{ openio_kibana_serviceid }}/kibana.yml"
    - src: "gridinit_kibana.conf.j2"
      dest: "{{ openio_kibana_gridinit_dir }}/{{ openio_kibana_gridinit_file_prefix }}\
        kibana-{{ openio_kibana_serviceid }}.conf"
  register: _kibana_conf

- name: Install kibana safeguard plugin
  command: "./bin/kibana-plugin install {{ openio_kibana_safeguard_version }}"
  register: _sg_installed
  args:
    chdir: "/usr/share/kibana"
  when:
    - openio_kibana_safeguard_version != ""
  failed_when:
    - _sg_installed.rc != 0
    - not 'already exists' in _sg_installed.stderr

- name: restart kibana
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_kibana_namespace}}-kibana-{{openio_kibana_serviceid}}
  when:
    - _kibana_conf.changed
    - not openio_kibana_provision_only
  tags: configure
...
